from sqlalchemy import Column, Integer, String, DECIMAL
from database import Base


class Peaje(Base):
    __tablename__ = "peajes"

    id = Column(Integer, primary_key=True)
    X = Column(String(17))
    Y = Column(String(16))
    objectid = Column(Integer)
    codigotramo = Column(String(8))
    postereferencia = Column(Integer)
    distanciaposte = Column(Integer)
    nombrepeaje = Column(String(26))
    latitud = Column(DECIMAL(10, 8))
    longitud = Column(DECIMAL(11, 8))
    categoriai = Column(Integer)
    categoriaii = Column(Integer)
    categoriaiii = Column(String(5))
    categoriaiv = Column(Integer)
    categoriav = Column(Integer)
    categoriavi = Column(Integer)
    categoriavii = Column(Integer)
    linkfoto = Column(String(70))
    sector = Column(String(70))
    responsable = Column(String(50))
    sentido = Column(String(99))
    ubicacion = Column(String(121))
    telefonopeaje = Column(String(93))
    telefonogrua = Column(String(161))
    ejeadicional = Column(String(5))
    ejeadicionalr = Column(String(5))
    ejegrua = Column(String(5))
    categoriaeie = Column(String(4))
    categoriaviii = Column(String(4))
    categoriaix = Column(String(4))
    categoriaiex = Column(String(4))
    categoriaiee = Column(String(4))
    categoriaieee = Column(String(4))
    categoriaiia = Column(String(4))
    categoriaeae = Column(String(1))
    categoriaec = Column(String(4))
    categoriae = Column(String(4))
    categoriaie = Column(String(5))
    categoriaiie = Column(String(5))
    categoriaiiie = Column(String(5))
    categoriaive = Column(String(5))
    categoriave = Column(String(5))
    categoriavie = Column(String(5))
    categoriaviie = Column(String(5))
    codigopeaje = Column(String(3))
    administrador = Column(String(1))
    territorial = Column(String(2))
    globalid = Column(String(38))
    created_user = Column(String(17))
    created_date = Column(String(22))
    last_edited_user = Column(String(17))
    last_edited_date = Column(String(22))
